upload_threshold = 100
upload_process_batch_size = 1000

[server]
host = "127.0.0.1"
port = 8443
mode = "http"     # Options: "http" or "https"

[server.ssl]
cert_file = "/etc/ssl/certs/cosdata-ssl.crt"
key_file = "/etc/ssl/private/cosdata-ssl.key"
