upload_threshold = 100
upload_process_batch_size = 1000

[server]
host = "127.0.0.1"
port = 8443
mode = "https"     # Options: "http" or "https"

[server.ssl]
cert_file = "/home/hitentandon/.certs/certs/cosdata-ssl.crt"
key_file = "/home/hitentandon/.certs/private/cosdata-ssl.key"
